# Nginx Dockerfile
FROM nginx:1.27

# Copy Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy built static frontend
COPY dist/device-app/browser /usr/share/nginx/html

# Expose frontend port
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
